server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/ccuap_demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=GMT%2b8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6399
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiyun.entity
  configuration:
    map-underscore-to-camel-case: true
# 与微信相关的配置
wechat:
  # 微信公众号的应用id
  appId:
  # 密钥
  secret:
  # 获取基础access_token的接口
  accessTokenUrl:  https://api.weixin.qq.com/cgi-bin/token
  # 创建菜单的接口
  menuUrl: https://api.weixin.qq.com/cgi-bin/menu/create
  # 通过UID机制获取用户信息的接口
  userInfoUrl: https://api.weixin.qq.com/cgi-bin/user/info
  # 网页授权时，通过code获取access_token和openid的接口
  loginTokenUrl:  https://api.weixin.qq.com/sns/jscode2session?appid=
  # 根据access_token(非基础access_token)和openid换取用户信息的接口
  loginInfoUrl: https://api.weixin.qq.com/sns/userinfo
  # 发送模板消息的接口
  templateMsgUrl: https://api.weixin.qq.com/cgi-bin/message/template/send